spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gdfuture_db?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: Decembrie2001
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  jwt:
    secretKey: asdasdasdasdasd123344asdasdasdasdasasd12321332sadas
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 7

  mail:
    host: smtp.gmail.com
    port: 587
    username: globaldevelopmentfuture@gmail.com
    password: ahmrurphyuxgibfx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
server:
  error:
    include-binding-errors: always
    include-message: always

cloudflare:
  r2:
    endpoint: "https://59714e0c03cca5e1ffc8f27e9c10a008.r2.cloudflarestorage.com"
    bucket: "gdfuture"
    access-key: "c4075cfcbbeba88a5bb00fb637fb1776"
    secret-key: "a1158fee0fb8064d3fa1c9dfb91702121fc40779aafb5b72dd6ebe8f4c7b671e"

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true


app:
  base:
    url: http://localhost:3000